return { 
"vvadd_double_double_double", 
"vvadd_double_float_double", 
"vvadd_double_int16_t_double", 
"vvadd_double_int32_t_double", 
"vvadd_double_int64_t_double", 
"vvadd_double_int8_t_double", 

"vvadd_float_double_double", 
"vvadd_float_float_float", 
"vvadd_float_int16_t_float", 
"vvadd_float_int32_t_float", 
"vvadd_float_int64_t_double", 
"vvadd_float_int8_t_float", 

"vvadd_int64_t_double_double", 
"vvadd_int64_t_float_double", 
"vvadd_int64t_int16_t_int64_t", 
"vvadd_int64_t_int32_t_int64_t", 
"vvadd_int64_t_int64_t_int64_t", 
"vvadd_int64_t_int8_t_int64_t", 

"vvadd_int32_t_double_double", 
"vvadd_int32_t_float_float", 
"vvadd_int32t_int16_t_int32_t", 
"vvadd_int32_t_int32_t_int32_t", 
"vvadd_int32_t_int64_t_int64_t", 
"vvadd_int32_t_int8_t_int32_t", 

"vvadd_int16_t_double_double", 
"vvadd_int16_t_float_float", 
"vvadd_int16t_int16_t_int16_t", 
"vvadd_int16_t_int32_t_int32_t", 
"vvadd_int16_t_int64_t_int64_t", 
"vvadd_int16_t_int8_t_int16_t", 

"vvadd_int8_t_double_double", 
"vvadd_int8_t_float_float", 
"vvadd_int8t_int16_t_int16_t", 
"vvadd_int8_t_int32_t_int32_t", 
"vvadd_int8_t_int64_t_int64_t", 
"vvadd_int8_t_int8_t_int8_t", 
}
